/**
 * 普通声母拼音，不含 jqx 和 zh/ch/sh/r/z/c/s。
 * 由 scripts/gentest.ts 自动生成，勿手动修改。
 */

import { describe, expect, it } from 'vitest'
import { invn2invnz, invn2pinyin, invnz2invn, invnz2pinyin, pinyin2invn, pinyin2invnz } from '../src/main'

const DATA: [string, string, string][] = [
  // i (头)
  ['bi', 'bi', '⿱匕一'],
  ['pi', 'pi', '⿱片一'],
  ['mi', 'mi', '⿱木一'],
  ['di', 'di', '⿱歹一'],
  ['ti', 'ti', '⿱屯一'],
  ['ni', 'ni', '⿱牛一'],
  ['li', 'li', '⿱立一'],
  // u (头)
  ['bu', 'bu', '⿰匕土'],
  ['pu', 'pu', '⿰片土'],
  ['mu', 'mu', '⿰木土'],
  ['fu', 'fu', '⿰方土'],
  ['du', 'du', '⿰歹土'],
  ['tu', 'tu', '⿰屯土'],
  ['nu', 'nu', '⿰牛土'],
  ['lu', 'lu', '⿰立土'],
  ['gu', 'gu', '⿰弓土'],
  ['ku', 'ku', '⿰口土'],
  ['hu', 'hu', '⿰火土'],
  // ü (头)
  ['nü', 'nv', '⿰牛女'],
  ['lü', 'lv', '⿰立女'],
  // ai (腹)
  ['bai', 'ba', '⿰匕才'],
  ['pai', 'pa', '⿰片才'],
  ['mai', 'ma', '⿰木才'],
  ['dai', 'da', '⿰歹才'],
  ['tai', 'ta', '⿰屯才'],
  ['nai', 'na', '⿰牛才'],
  ['lai', 'la', '⿰立才'],
  ['gai', 'ga', '⿰弓才'],
  ['kai', 'ka', '⿰口才'],
  ['hai', 'ha', '⿰火才'],
  // ei (腹)
  ['bei', 'be', '⿰匕巿'],
  ['pei', 'pe', '⿰片巿'],
  ['mei', 'me', '⿰木巿'],
  ['fei', 'fe', '⿰方巿'],
  ['dei', 'de', '⿰歹巿'],
  ['nei', 'ne', '⿰牛巿'],
  ['lei', 'le', '⿰立巿'],
  ['gei', 'ge', '⿰弓巿'],
  ['hei', 'he', '⿰火巿'],
  // ou (腹)
  ['pou', 'po', '⿰片斗'],
  ['mou', 'mo', '⿰木斗'],
  ['fou', 'fo', '⿰方斗'],
  ['dou', 'do', '⿰歹斗'],
  ['tou', 'to', '⿰屯斗'],
  ['nou', 'no', '⿰牛斗'],
  ['lou', 'lo', '⿰立斗'],
  ['gou', 'go', '⿰弓斗'],
  ['kou', 'ko', '⿰口斗'],
  ['hou', 'ho', '⿰火斗'],
  // a (腹)
  ['ba', 'baa', '⿰匕八'],
  ['pa', 'paa', '⿰片八'],
  ['ma', 'maa', '⿰木八'],
  ['fa', 'faa', '⿰方八'],
  ['da', 'daa', '⿰歹八'],
  ['ta', 'taa', '⿰屯八'],
  ['na', 'naa', '⿰牛八'],
  ['la', 'laa', '⿰立八'],
  ['ga', 'gaa', '⿰弓八'],
  ['ka', 'kaa', '⿰口八'],
  ['ha', 'haa', '⿰火八'],
  // o (腹)
  ['bo', 'boo', '⿰匕乇'],
  ['po', 'poo', '⿰片乇'],
  ['mo', 'moo', '⿰木乇'],
  ['fo', 'foo', '⿰方乇'],
  // e (腹)
  ['me', 'mee', '⿰木戈'],
  ['de', 'dee', '⿰歹戈'],
  ['te', 'tee', '⿰屯戈'],
  ['ne', 'nee', '⿰牛戈'],
  ['le', 'lee', '⿰立戈'],
  ['ge', 'gee', '⿰弓戈'],
  ['ke', 'kee', '⿰口戈'],
  ['he', 'hee', '⿰火戈'],
  // ao (腹)
  ['bao', 'bao', '⿰匕刀'],
  ['pao', 'pao', '⿰片刀'],
  ['mao', 'mao', '⿰木刀'],
  ['dao', 'dao', '⿰歹刀'],
  ['tao', 'tao', '⿰屯刀'],
  ['nao', 'nao', '⿰牛刀'],
  ['lao', 'lao', '⿰立刀'],
  ['gao', 'gao', '⿰弓刀'],
  ['kao', 'kao', '⿰口刀'],
  ['hao', 'hao', '⿰火刀'],
  // en (尾)
  ['ben', 'bn', '⿵冂匕'],
  ['pen', 'pn', '⿵冂片'],
  ['men', 'mn', '⿵冂木'],
  ['fen', 'fn', '⿵冂方'],
  ['den', 'dn', '⿵冂歹'],
  ['nen', 'nn', '⿵冂牛'],
  ['gen', 'gn', '⿵冂弓'],
  ['ken', 'kn', '⿵冂口'],
  ['hen', 'hn', '⿵冂火'],
  // eng (尾)
  ['beng', 'bg', '⿹勹匕'],
  ['peng', 'pg', '⿹勹片'],
  ['meng', 'mg', '⿹勹木'],
  ['feng', 'fg', '⿹勹方'],
  ['deng', 'dg', '⿹勹歹'],
  ['teng', 'tg', '⿹勹屯'],
  ['neng', 'ng', '⿹勹牛'],
  ['leng', 'lg', '⿹勹立'],
  ['geng', 'gg', '⿹勹弓'],
  ['keng', 'kg', '⿹勹口'],
  ['heng', 'hg', '⿹勹火'],
  // ie (头腹)
  ['bie', 'bia', '⿰匕⿱一才'],
  ['pie', 'pia', '⿰片⿱一才'],
  ['mie', 'mia', '⿰木⿱一才'],
  ['die', 'dia', '⿰歹⿱一才'],
  ['tie', 'tia', '⿰屯⿱一才'],
  ['nie', 'nia', '⿰牛⿱一才'],
  ['lie', 'lia', '⿰立⿱一才'],
  // iu (头腹)
  ['miu', 'mio', '⿰木⿱一斗'],
  ['diu', 'dio', '⿰歹⿱一斗'],
  ['niu', 'nio', '⿰牛⿱一斗'],
  ['liu', 'lio', '⿰立⿱一斗'],
  // ia (头腹)
  ['dia', 'diaa', '⿰歹⿱一八'],
  // iao (头腹)
  ['biao', 'biao', '⿰匕⿱一刀'],
  ['piao', 'piao', '⿰片⿱一刀'],
  ['miao', 'miao', '⿰木⿱一刀'],
  ['diao', 'diao', '⿰歹⿱一刀'],
  ['tiao', 'tiao', '⿰屯⿱一刀'],
  ['niao', 'niao', '⿰牛⿱一刀'],
  ['liao', 'liao', '⿰立⿱一刀'],
  // uai (头腹)
  ['guai', 'gua', '⿰弓⿱土才'],
  ['kuai', 'kua', '⿰口⿱土才'],
  ['huai', 'hua', '⿰火⿱土才'],
  // ui (头腹)
  ['dui', 'due', '⿰歹⿱土巿'],
  ['tui', 'tue', '⿰屯⿱土巿'],
  ['gui', 'gue', '⿰弓⿱土巿'],
  ['kui', 'kue', '⿰口⿱土巿'],
  ['hui', 'hue', '⿰火⿱土巿'],
  // ua (头腹)
  ['gua', 'guaa', '⿰弓⿱土八'],
  ['kua', 'kuaa', '⿰口⿱土八'],
  ['hua', 'huaa', '⿰火⿱土八'],
  // uo (头腹)
  ['duo', 'duoo', '⿰歹⿱土乇'],
  ['tuo', 'tuoo', '⿰屯⿱土乇'],
  ['nuo', 'nuoo', '⿰牛⿱土乇'],
  ['luo', 'luoo', '⿰立⿱土乇'],
  ['guo', 'guoo', '⿰弓⿱土乇'],
  ['kuo', 'kuoo', '⿰口⿱土乇'],
  ['huo', 'huoo', '⿰火⿱土乇'],
  // üe (头腹)
  ['nüe', 'nva', '⿰牛⿱女才'],
  ['lüe', 'lva', '⿰立⿱女才'],
  // in (头尾)
  ['bin', 'bin', '⿰匕⿵冂一'],
  ['pin', 'pin', '⿰片⿵冂一'],
  ['min', 'min', '⿰木⿵冂一'],
  ['nin', 'nin', '⿰牛⿵冂一'],
  ['lin', 'lin', '⿰立⿵冂一'],
  // ing (头尾)
  ['bing', 'big', '⿰匕⿹勹一'],
  ['ping', 'pig', '⿰片⿹勹一'],
  ['ming', 'mig', '⿰木⿹勹一'],
  ['ding', 'dig', '⿰歹⿹勹一'],
  ['ting', 'tig', '⿰屯⿹勹一'],
  ['ning', 'nig', '⿰牛⿹勹一'],
  ['ling', 'lig', '⿰立⿹勹一'],
  // un (头尾)
  ['dun', 'dun', '⿰歹⿵冂土'],
  ['tun', 'tun', '⿰屯⿵冂土'],
  ['nun', 'nun', '⿰牛⿵冂土'],
  ['lun', 'lun', '⿰立⿵冂土'],
  ['gun', 'gun', '⿰弓⿵冂土'],
  ['kun', 'kun', '⿰口⿵冂土'],
  ['hun', 'hun', '⿰火⿵冂土'],
  // ong (头尾)
  ['dong', 'dug', '⿰歹⿹勹土'],
  ['tong', 'tug', '⿰屯⿹勹土'],
  ['nong', 'nug', '⿰牛⿹勹土'],
  ['long', 'lug', '⿰立⿹勹土'],
  ['gong', 'gug', '⿰弓⿹勹土'],
  ['kong', 'kug', '⿰口⿹勹土'],
  ['hong', 'hug', '⿰火⿹勹土'],
  // an (腹尾)
  ['ban', 'ban', '⿰匕⿵冂才'],
  ['pan', 'pan', '⿰片⿵冂才'],
  ['man', 'man', '⿰木⿵冂才'],
  ['fan', 'fan', '⿰方⿵冂才'],
  ['dan', 'dan', '⿰歹⿵冂才'],
  ['tan', 'tan', '⿰屯⿵冂才'],
  ['nan', 'nan', '⿰牛⿵冂才'],
  ['lan', 'lan', '⿰立⿵冂才'],
  ['gan', 'gan', '⿰弓⿵冂才'],
  ['kan', 'kan', '⿰口⿵冂才'],
  ['han', 'han', '⿰火⿵冂才'],
  // ang (腹尾)
  ['bang', 'bag', '⿰匕⿹勹才'],
  ['pang', 'pag', '⿰片⿹勹才'],
  ['mang', 'mag', '⿰木⿹勹才'],
  ['fang', 'fag', '⿰方⿹勹才'],
  ['dang', 'dag', '⿰歹⿹勹才'],
  ['tang', 'tag', '⿰屯⿹勹才'],
  ['nang', 'nag', '⿰牛⿹勹才'],
  ['lang', 'lag', '⿰立⿹勹才'],
  ['gang', 'gag', '⿰弓⿹勹才'],
  ['kang', 'kag', '⿰口⿹勹才'],
  ['hang', 'hag', '⿰火⿹勹才'],
  // ian (头腹尾)
  ['bian', 'bian', '⿰匕⿱一⿵冂才'],
  ['pian', 'pian', '⿰片⿱一⿵冂才'],
  ['mian', 'mian', '⿰木⿱一⿵冂才'],
  ['dian', 'dian', '⿰歹⿱一⿵冂才'],
  ['tian', 'tian', '⿰屯⿱一⿵冂才'],
  ['nian', 'nian', '⿰牛⿱一⿵冂才'],
  ['lian', 'lian', '⿰立⿱一⿵冂才'],
  // iang (头腹尾)
  ['niang', 'niag', '⿰牛⿱一⿹勹才'],
  ['liang', 'liag', '⿰立⿱一⿹勹才'],
  // uan (头腹尾)
  ['duan', 'duan', '⿰歹⿱土⿵冂才'],
  ['tuan', 'tuan', '⿰屯⿱土⿵冂才'],
  ['nuan', 'nuan', '⿰牛⿱土⿵冂才'],
  ['luan', 'luan', '⿰立⿱土⿵冂才'],
  ['guan', 'guan', '⿰弓⿱土⿵冂才'],
  ['kuan', 'kuan', '⿰口⿱土⿵冂才'],
  ['huan', 'huan', '⿰火⿱土⿵冂才'],
  // uang (头腹尾)
  ['guang', 'guag', '⿰弓⿱土⿹勹才'],
  ['kuang', 'kuag', '⿰口⿱土⿹勹才'],
  ['huang', 'huag', '⿰火⿱土⿹勹才'],
]

describe('普通声母（b p m f d t n l g k h）', () => {
  it.each(DATA)(
    '%s → %s → %s',
    (pinyin, invn, invnz) => {
      expect(invnz2pinyin(invnz)).toBe(pinyin)
      expect(pinyin2invnz(pinyin)).toBe(invnz)
      expect(invn2pinyin(invn)).toBe(pinyin)
      expect(pinyin2invn(pinyin)).toBe(invn)
      expect(invn2invnz(invn)).toBe(invnz)
      expect(invnz2invn(invnz)).toBe(invn)
    },
  )
})
