/**
 * 舌尖/卷舌声母拼音。
 * 全部 124 条，由 scripts/gen-test-data.ts 自动生成，勿手动修改。
 */

import { describe, expect, it } from 'vitest'
import { pinin2invnzChars, pinyin2pinin } from '../src/main'

const DATA: [string, string, string][] = [
  ['zha', 'zhaa', '⿰止八'],
  ['zhe', 'zhee', '⿰止么'],
  ['zhai', 'zha', '⿰止才'],
  ['zhei', 'zhe', '⿰止贝'],
  ['zhao', 'zhao', '⿰止刀'],
  ['zhou', 'zho', '⿰止斗'],
  ['zhan', 'zhan', '⿰止⿵冂才'],
  ['zhen', 'zhen', '⿰止⿵冂贝'],
  ['zhang', 'zhag', '⿰止⿹勹才'],
  ['zheng', 'zheg', '⿰止⿹勹贝'],
  ['zhi', 'zhi', '⿱止一'],
  ['zhu', 'zhu', '⿰止土'],
  ['zhua', 'zhuaa', '⿰止⿱土八'],
  ['zhuo', 'zhuee', '⿰止⿱土么'],
  ['zhuai', 'zhua', '⿰止⿱土才'],
  ['zhui', 'zhue', '⿰止⿱土贝'],
  ['zhuan', 'zhuan', '⿰止⿱土⿵冂才'],
  ['zhun', 'zhun', '⿰止⿵冂土'],
  ['zhuang', 'zhuag', '⿰止⿱土⿹勹才'],
  ['zhong', 'zhug', '⿰止⿹勹土'],
  ['cha', 'chaa', '⿸厂八'],
  ['che', 'chee', '⿸厂么'],
  ['chai', 'cha', '⿸厂才'],
  ['chao', 'chao', '⿸厂刀'],
  ['chou', 'cho', '⿸厂斗'],
  ['chan', 'chan', '⿸厂⿵冂才'],
  ['chen', 'chen', '⿸厂⿵冂贝'],
  ['chang', 'chag', '⿸厂⿹勹才'],
  ['cheng', 'cheg', '⿸厂⿹勹贝'],
  ['chi', 'chi', '⿱厂一'],
  ['chu', 'chu', '⿸厂土'],
  ['chua', 'chuaa', '⿸厂⿱土八'],
  ['chuo', 'chuee', '⿸厂⿱土么'],
  ['chuai', 'chua', '⿸厂⿱土才'],
  ['chui', 'chue', '⿸厂⿱土贝'],
  ['chuan', 'chuan', '⿸厂⿱土⿵冂才'],
  ['chun', 'chun', '⿸厂⿵冂土'],
  ['chuang', 'chuag', '⿸厂⿱土⿹勹才'],
  ['chong', 'chug', '⿸厂⿹勹土'],
  ['sha', 'shaa', '⿰山八'],
  ['she', 'shee', '⿰山么'],
  ['shai', 'sha', '⿰山才'],
  ['shei', 'she', '⿰山贝'],
  ['shao', 'shao', '⿰山刀'],
  ['shou', 'sho', '⿰山斗'],
  ['shan', 'shan', '⿰山⿵冂才'],
  ['shen', 'shen', '⿰山⿵冂贝'],
  ['shang', 'shag', '⿰山⿹勹才'],
  ['sheng', 'sheg', '⿰山⿹勹贝'],
  ['shi', 'shi', '⿱山一'],
  ['shu', 'shu', '⿰山土'],
  ['shua', 'shuaa', '⿰山⿱土八'],
  ['shuo', 'shuee', '⿰山⿱土么'],
  ['shuai', 'shua', '⿰山⿱土才'],
  ['shui', 'shue', '⿰山⿱土贝'],
  ['shuan', 'shuan', '⿰山⿱土⿵冂才'],
  ['shun', 'shun', '⿰山⿵冂土'],
  ['shuang', 'shuag', '⿰山⿱土⿹勹才'],
  ['ra', 'raa', '⿰日八'],
  ['re', 'ree', '⿰日么'],
  ['rao', 'rao', '⿰日刀'],
  ['rou', 'ro', '⿰日斗'],
  ['ran', 'ran', '⿰日⿵冂才'],
  ['ren', 'ren', '⿰日⿵冂贝'],
  ['rang', 'rag', '⿰日⿹勹才'],
  ['reng', 'reg', '⿰日⿹勹贝'],
  ['ri', 'ri', '⿱日一'],
  ['ru', 'ru', '⿰日土'],
  ['rua', 'ruaa', '⿰日⿱土八'],
  ['ruo', 'ruee', '⿰日⿱土么'],
  ['rui', 'rue', '⿰日⿱土贝'],
  ['ruan', 'ruan', '⿰日⿱土⿵冂才'],
  ['run', 'run', '⿰日⿵冂土'],
  ['rong', 'rug', '⿰日⿹勹土'],
  ['za', 'zaa', '⿰子八'],
  ['ze', 'zee', '⿰子么'],
  ['zai', 'za', '⿰子才'],
  ['zei', 'ze', '⿰子贝'],
  ['zao', 'zao', '⿰子刀'],
  ['zou', 'zo', '⿰子斗'],
  ['zan', 'zan', '⿰子⿵冂才'],
  ['zen', 'zen', '⿰子⿵冂贝'],
  ['zang', 'zag', '⿰子⿹勹才'],
  ['zeng', 'zeg', '⿰子⿹勹贝'],
  ['zi', 'zi', '⿱子一'],
  ['zu', 'zu', '⿰子土'],
  ['zuo', 'zuee', '⿰子⿱土么'],
  ['zui', 'zue', '⿰子⿱土贝'],
  ['zuan', 'zuan', '⿰子⿱土⿵冂才'],
  ['zun', 'zun', '⿰子⿵冂土'],
  ['zong', 'zug', '⿰子⿹勹土'],
  ['ca', 'caa', '⿱艹八'],
  ['ce', 'cee', '⿱艹么'],
  ['cai', 'ca', '⿱艹才'],
  ['cao', 'cao', '⿱艹刀'],
  ['cou', 'co', '⿱艹斗'],
  ['can', 'can', '⿱艹⿵冂才'],
  ['cen', 'cen', '⿱艹⿵冂贝'],
  ['cang', 'cag', '⿱艹⿹勹才'],
  ['ceng', 'ceg', '⿱艹⿹勹贝'],
  ['ci', 'ci', '⿱艹一'],
  ['cu', 'cu', '⿱艹土'],
  ['cuo', 'cuee', '⿱艹⿱土么'],
  ['cui', 'cue', '⿱艹⿱土贝'],
  ['cuan', 'cuan', '⿱艹⿱土⿵冂才'],
  ['cun', 'cun', '⿱艹⿵冂土'],
  ['cong', 'cug', '⿱艹⿹勹土'],
  ['sa', 'saa', '⿰纟八'],
  ['se', 'see', '⿰纟么'],
  ['sai', 'sa', '⿰纟才'],
  ['sei', 'se', '⿰纟贝'],
  ['sao', 'sao', '⿰纟刀'],
  ['sou', 'so', '⿰纟斗'],
  ['san', 'san', '⿰纟⿵冂才'],
  ['sen', 'sen', '⿰纟⿵冂贝'],
  ['sang', 'sag', '⿰纟⿹勹才'],
  ['seng', 'seg', '⿰纟⿹勹贝'],
  ['si', 'si', '⿱纟一'],
  ['su', 'su', '⿰纟土'],
  ['suo', 'suee', '⿰纟⿱土么'],
  ['sui', 'sue', '⿰纟⿱土贝'],
  ['suan', 'suan', '⿰纟⿱土⿵冂才'],
  ['sun', 'sun', '⿰纟⿵冂土'],
  ['song', 'sug', '⿰纟⿹勹土'],
]

describe('舌尖/卷舌音（zh ch sh r z c s）', () => {
  it.each(DATA)(
    '%s → %s → %s',
    (pinyin, pinin, invnz) => {
      expect(pinyin2pinin(pinyin)).toBe(pinin)
      expect(pinin2invnzChars(pinin)).toBe(invnz)
    },
  )
})
