import { readFileSync, writeFileSync } from 'node:fs'
import opentype from 'opentype.js'

const FONT_PATH = 'C:/Windows/Fonts/DENG.TTF'
const OUTPUT_PATH = 'tutorial/.vitepress/theme/invnz-glyphs.ts'

const CHARS = '一才斗八刀女冂勹土贝乇么耳匕丁工久七忄止厂山日子艹纟'

function main() {
  const buf = readFileSync(FONT_PATH)
  const font = opentype.parse(buf)

  interface GlyphData {
    d: string
    x: number
    y: number
    w: number
    h: number
    advance: number
  }

  const glyphs: Record<string, GlyphData> = {}

  for (const c of CHARS) {
    const glyph = font.charToGlyph(c)
    const path = font.getPath(c, 0, 0, font.unitsPerEm)
    const bbox = path.getBoundingBox()
    glyphs[c] = {
      d: path.toSVG(),
      x: bbox.x1,
      y: bbox.y1,
      w: bbox.x2 - bbox.x1,
      h: bbox.y2 - bbox.y1,
      advance: glyph.advanceWidth,
    }
  }

  const code = `// Auto-generated by scripts/extract-glyphs.ts
// Source: DengXian (sans-serif CJK font)

export interface GlyphData {
  d: string
  x: number
  y: number
  w: number
  h: number
  advance: number
}

export const UNITS_PER_EM = ${font.unitsPerEm}

export const GLYPHS: Record<string, GlyphData> = ${JSON.stringify(glyphs, null, 2)}
`

  writeFileSync(OUTPUT_PATH, code, 'utf-8')
  console.log(`Generated ${OUTPUT_PATH} with ${Object.keys(glyphs).length} glyphs`)
}

main()
