/**
 * 构建脚本：从 zi.tools 预取 invenz SVG 路径数据。
 */
import { writeFileSync } from 'node:fs'
import { pinyinTable } from '../src/data/pinyinTable'
import { getInvnz } from '../src/main'

const ZU_ZI_API = 'http://zu.zi.tools/'
const OUTPUT_PATH = 'tutorial/.vitepress/theme/invnz-glyphs.ts'
const TIMEOUT_MS = 10000
const CONCURRENCY = 20

async function fetchPaths(charOrIds: string): Promise<string[] | null> {
  const url = `${ZU_ZI_API}${encodeURIComponent(charOrIds)}.svg`
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(TIMEOUT_MS) })
    if (!res.ok)
      return null
    const text = await res.text()
    const paths: string[] = []
    const regex = /<path\s+d="((?:[^"\\]|\\.)*)"/g
    let match
    while ((match = regex.exec(text)) !== null)
      paths.push(match[1])
    return paths.length > 0 ? paths : null
  }
  catch {
    return null
  }
}

async function batchFetch<T>(items: T[], keyFn: (item: T) => string, label: string):
Promise<[Record<string, string[]>, number, number]> {
  const result: Record<string, string[]> = {}
  let ok = 0; let fail = 0
  console.log(`\n开始 ${label} (共 ${items.length} 条, 并发 ${CONCURRENCY})`)
  for (let i = 0; i < items.length; i += CONCURRENCY) {
    const batch = items.slice(i, i + CONCURRENCY)
    const results = await Promise.all(
      batch.map(async (item) => {
        const key = keyFn(item)
        const paths = await fetchPaths(key)
        return { key, paths }
      }),
    )
    for (const { key, paths } of results) {
      if (paths) { result[key] = paths; ok++ }
      else { fail++ }
    }
    const pct = Math.min(i + CONCURRENCY, items.length)
    if (pct % 100 === 0 || pct >= items.length)
      console.log(`  进度: ${pct}/${items.length} | 成功: ${ok} 失败: ${fail}`)
  }
  return [result, ok, fail]
}

const FINALS = [
  'a',
  'o',
  'e',
  'ai',
  'ei',
  'ao',
  'ou',
  'an',
  'en',
  'ang',
  'eng',
  'er',
  'i',
  'ia',
  'ie',
  'iao',
  'iu',
  'ian',
  'in',
  'iang',
  'ing',
  'iong',
  'u',
  'ua',
  'uo',
  'uai',
  'ui',
  'uan',
  'un',
  'uang',
  'ong',
  'ü',
  'üe',
  'üan',
  'ün',
]

const ZERO: Record<string, string> = {
  a: 'a',
  o: 'o',
  e: 'e',
  ai: 'ai',
  ei: 'ei',
  ao: 'ao',
  ou: 'ou',
  an: 'an',
  en: 'en',
  ang: 'ang',
  eng: 'eng',
  er: 'er',
  i: 'yi',
  ia: 'ya',
  ie: 'ye',
  iao: 'yao',
  iu: 'you',
  ian: 'yan',
  in: 'yin',
  iang: 'yang',
  ing: 'ying',
  iong: 'yong',
  u: 'wu',
  ua: 'wa',
  uo: 'wo',
  uai: 'wai',
  ui: 'wei',
  uan: 'wan',
  un: 'wen',
  uang: 'wang',
  ong: 'ong',
  ü: 'yu',
  üe: 'yue',
  üan: 'yuan',
  ün: 'yun',
}

async function main() {
  // 1. 生成所有音节和对应的 invenz
  const invenzSet = new Set<string>()

  // 零声母音节
  for (const f of FINALS) {
    const p = ZERO[f]
    if (p) {
      const invnz = getInvnz(p)
      if (invnz)
        invenzSet.add(invnz)
    }
  }

  // 声母+韵母音节
  for (const [init, finals] of Object.entries(pinyinTable)) {
    if (init === 'zero')
      continue
    for (const f of finals) {
      const pinyin = 'jqx'.includes(init) && f.startsWith('ü')
        ? init + f.replace('ü', 'u')
        : init + f
      const invnz = getInvnz(pinyin)
      if (invnz)
        invenzSet.add(invnz)
    }
  }

  const allIds = [...invnzSet].sort()
  const idcExps = allIds.filter(s => '⿰⿱⿸⿹⿵'.includes(s[0]))
  const singleChars = allIds.filter(s => s.length === 1 && !'⿰⿱⿸⿹⿵'.includes(s[0]))

  console.log(`总 invenz 表达式: ${allIds.length}`)
  console.log(`  IDC 表达式: ${idcExps.length}`)
  console.log(`  纯单字: ${singleChars.length}`)

  // 2. 收集所有需兜底的单字
  const rootChars = new Set<string>(singleChars)
  for (const ids of idcExps) {
    for (const ch of ids) {
      if (!'⿰⿱⿸⿹⿵'.includes(ch))
        rootChars.add(ch)
    }
  }
  for (const ch of '田艹纟贝丁么工久山忄厂')
    rootChars.add(ch)

  // 3. 预取 IDC 表达式
  const [idsResult, idsOk, idsFail] = await batchFetch(
    idcExps,
    s => s,
    'IDC 表达式',
  )

  // 4. 预取单字
  const sortedChars = [...rootChars].sort()
  const [charResult, charOk, charFail] = await batchFetch(
    sortedChars,
    s => s,
    '单字',
  )

  // 5. 生成文件
  const code = `// Auto-generated by scripts/extract-ids-svgs.ts
// Source: zi.tools (http://zu.zi.tools/)

export interface InvnzGlyphData {
  strokes: string[]
}

export const IDS_SVGS: Record<string, InvnzGlyphData> = ${JSON.stringify(
  Object.fromEntries(Object.entries(idsResult).map(([k, v]) => [k, { strokes: v }])),
  null,
  2,
)}

export const CHAR_SVGS: Record<string, InvnzGlyphData> = ${JSON.stringify(
  Object.fromEntries(Object.entries(charResult).map(([k, v]) => [k, { strokes: v }])),
  null,
  2,
)}

export const SVG_SIZE = 200
`

  writeFileSync(OUTPUT_PATH, code, 'utf-8')
  console.log(`\n=== 完成 ===`)
  console.log(`IDS_SVGS: ${Object.keys(idsResult).length} 条 (${idsOk}成功/${idsFail}失败)`)
  console.log(`CHAR_SVGS: ${Object.keys(charResult).length} 条 (${charOk}成功/${charFail}失败)`)
  console.log(`输出: ${OUTPUT_PATH}`)
}

main().catch(console.error)
